export const surpriseMePrompts = [
    'A lone figure standing at the edge of a vast, misty canyon',
    'A towering cityscape at sunset, with skyscrapers silhouetted against the sky',
    'A mysterious cave deep in the heart of a lush rainforest',
    'A colorful hot air balloon festival filling the sky',
    'A lone sailboat navigating through an endless sea of icebergs',
    'A beautiful snow-covered mountain range, with a bright blue sky overhead',
    'A surreal cityscape, with upside-down buildings and impossible architecture',
    'A tranquil lakeside scene, with mist rising from the water and a lone fisherman in a boat',
    'A majestic waterfall plunging into a crystal-clear pool below',
    'A peaceful village nestled in the foothills of a lush, green valley',
    'A breathtaking display of fireworks lighting up the night sky',
    'A surreal underwater landscape, with colorful coral and sea creatures swimming past',
    'A stunning natural arch formation, carved out of towering rock formations',
    'A misty, dreamlike forest with shafts of light shining through the trees',
    'A serene desert landscape, with sand dunes stretching to the horizon',
    'A beautiful, sparkling night sky filled with shooting stars and constellations',
    'A whimsical, colorful carnival scene with bright lights and rides',
    'A majestic, snow-capped mountain peak rising into the clouds',
    'A beautiful, sun-drenched field of wildflowers',
    'A surreal, otherworldly landscape with floating islands and strange creatures',
    'A dark and stormy seascape, with towering waves crashing against the rocks',
    'A beautiful, ornate palace with towering spires and intricate carvings',
    'A lush, tropical jungle with hidden waterfalls and exotic wildlife',
    'A serene, misty morning scene with a lone cabin by a lake',
    'A magical forest filled with giant, glowing mushrooms and fireflies',
    'A towering, ice-covered castle in a frozen wasteland',
    'A serene, snowy landscape with a single tree standing tall against the wind',
    'A colorful, chaotic city street filled with people and neon lights',
    'A serene beach scene with gentle waves and colorful sunsets',
    'A surreal dreamscape filled with floating clouds and impossible geometry',
];